### ISSUE TITLE
from object_detection.protos import string_int_label_map_pb2

### ISSUE THREAD

**Issue by Elie60** [nicknochnack/RealTimeSignLanguageDetectionwithTFJS#5]
When a run this code, I get this error

```
!python3 {SCRIPTS_PATH + '/generate_tfrecord.py'} -x {IMAGE_PATH + '/train'} -l {ANNOTATION_PATH + '/label_map.pbtxt'} -o {ANNOTATION_PATH + '/train.record'}
!python3 {SCRIPTS_PATH + '/generate_tfrecord.py'} -x {IMAGE_PATH + '/test'} -l {ANNOTATION_PATH + '/label_map.pbtxt'} -o {ANNOTATION_PATH + '/test.record'}
```

Traceback (most recent call last):
  File "/Users/mulamba/Desktop/XXX/RealTimeSignLanguageDetectionwithTFJS/Tensorflow/scripts/generate_tfrecord.py", line 29, in <module>
    from object_detection.utils import dataset_util, label_map_util
  File "/Users/mulamba/anaconda3/lib/python3.11/site-packages/object_detection/utils/label_map_util.py", line 21, in <module>
    from object_detection.protos import string_int_label_map_pb2
ImportError: cannot import name 'string_int_label_map_pb2' from 'object_detection.protos' (/Users/mulamba/anaconda3/lib/python3.11/site-packages/object_detection/protos/__init__.py)
Traceback (most recent call last):
  File "/Users/mulamba/Desktop/XXX/RealTimeSignLanguageDetectionwithTFJS/Tensorflow/scripts/generate_tfrecord.py", line 29, in <module>
    from object_detection.utils import dataset_util, label_map_util
  File "/Users/mulamba/anaconda3/lib/python3.11/site-packages/object_detection/utils/label_map_util.py", line 21, in <module>
    from object_detection.protos import string_int_label_map_pb2
ImportError: cannot import name 'string_int_label_map_pb2' from 'object_detection.protos' (/Users/mulamba/anaconda3/lib/python3.11/site-packages/object_detection/protos/__init__.py)
m

**Comment by KesavaChari-V** [comment]
Bro for me also same error 
If you sloved 
please post it like how it should be solved...
